place; 4; command=place; object=cube; name=target; material=Au; pos_x=0.0; pos_y=0.0; pos_z=0.0; rot_x=0.0; rot_y=0.0; rot_z=0.0; size_x=10.0; size_y=10.0; size_z=7.254000000000002e-05; 
place; 4; command=place; object=sphere; name=source_marker; material=vacuum; pos_x=0.0; pos_y=0.0; pos_z=-50.0; rot_x=0.0; rot_y=0.0; rot_z=0.0; radius=2.0; alpha=0.5; red=0; green=100; 
place; 4; command=place; object=sphere; name=detector; material=vacuum; pos_x=0.0; pos_y=0.0; pos_z=0.0; rot_x=0.0; rot_y=0.0; rot_z=0.0; radius=100; inner_radius=95.0; alpha=0.1; red=255; green=0; 
make_sd; 7; command=make_sd; attach=ldetector; name=RBS; particle=primary; attrib_0=ekin; attrib_1=theta; attrib_2=phi; attrib_count=3; 
make_sd; 7; command=make_sd; attach=ldetector; name=PIXE; particle=gamma; attrib_0=ekin; attrib_1=theta; attrib_2=phi; attrib_count=3; 
particle_source; 4; command=particle_source; particle=proton; mono_e=true; shape=beam; energy=0.4; sigma=0.0; x_pos=0; y_pos=0.0; z_pos=-50.0; x_facing=0; y_facing=0; z_facing=1; sigma_r=1; atomic_number=0; atomic_mass=0; charge=0; excitation=0; 
prerun_macro; 2; command=prerun_macro; content=/custom/ana/setOutFolder output_BonnRBS2_Au_proton_0-4; 
prerun_macro; 2; command=prerun_macro; content=/custom/ana/setRunName BonnRBS2_Au_proton_0-4_; 
no_macro_f; 1; command=no_macro_f; event_count=100000000.0; thread_count=12; 
